---
# Use root/123 as user/password credentials
version: '3.1'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./tables.sql:/docker-entrypoint-initdb.d/tables.sql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123

  adminer:
    image: adminer
    ports:
      - 8080:8080
